#!/bin/bash

if [[ $OSTYPE == darwin* ]]; then
  pbcopy
elif [[ $OSTYPE == cygwin* ]]; then
  cat > /dev/clipboard
else
  if [[ -x "$(command -v xclip)" ]]; then
    xclip -in -selection clipboard
  elif [[ -x "$(command -v xsel)" ]]; then
    xsel --clipboard --input
  else
    print "clipcopy: Platform $OSTYPE not supported or xclip/xsel not installed" >&2
    return 1
  fi
fi
