#!/bin/bash

# The rustup doc command seems to have trouble opening the html files within WSL2.
# This script will properly open the html documents in the browser.

if grep -qE "([Mm]icrosoft|WSL)" /proc/version &> /dev/null
then
    wsl_path="$(rustup doc --path $@)"

    if [ $? -ne 0 ]
    then
        exit 1
    fi

    win_path="$(wslpath -w $wsl_path)"

    if [ $? -eq 0 ]
    then
        wslview "$win_path"
    else
        wslview "$wsl_path"
    fi
else
    rustup doc "$@"
fi

