#!/usr/bin/env bash

# originally from https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer
# set environment variable TMUX_SESSIONIZER_DIRS to add more directories to search (only searches home by default)

if [[ $# -eq 1 ]]; then
    selected="$1"
else
    selected="$(find ~/ $TMUX_SESSIONIZER_DIRS -mindepth 1 -maxdepth 1 -type d | sort -u | fzf)"
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name="$(basename "$selected" | tr . _)"
has_session=$(tmux has-session -t="$selected_name" 2> /dev/null; echo $?)

if [[ -z $TMUX ]]; then # If not in a tmux session
    if [[ $has_session -ne 0 ]]; then # If session doesn't already exist, create it
        tmux new-session -s "$selected_name" -c "$selected"
        exit 0
    fi

    # Else attach to existing session
    tmux attach-session -t "$selected_name" -c "$selected"
    exit 0
fi

# If already in a tmux session, just attempt to switch over, but not create a new session
tmux switch-client -t "$selected_name"

