#!/usr/bin/env bash

# originally from https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

USAGE="$(basename $0) <options> [session_dir]

Args:
    -a : choose an existing session to attach onto
    -h : display usage and exit
    session_dir: directory to open in tmux session, choose from dirs set in \$TMUX_SESSIONIZER_DIRS if this arg isn't given"

while getopts "ha" flag; do
    case "$flag" in
        a) selected="$(tmux ls -F '#{session_name} (#{pane_current_path})' | fzf --select-1 --exit-0 | awk '{print $1}')"
            if [[ -z $selected ]]; then
                exit 0
            fi
            ;;
        h) echo "$USAGE" && exit 0 ;;
        *) echo "$USAGE" && exit 1 ;;
    esac
done

shift $(($OPTIND - 1))

if [[ -z $selected ]]; then
    if [[ $# -gt 0 ]]; then
        selected="$1"
    else
        selected="$(find ~/ $TMUX_SESSIONIZER_DIRS -mindepth 1 -maxdepth 1 -type d | sort -u | fzf)"
    fi
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name="$(basename "$selected" | tr . _)"
has_session=$(tmux has-session -t="$selected_name" 2> /dev/null; echo $?)

if [[ -z $TMUX ]]; then # If not in a tmux session
    if [[ $has_session -ne 0 ]]; then # If session doesn't already exist, create it
        tmux new-session -s "$selected_name" -c "$selected"
        exit 0
    fi

    # Else attach to existing session
    tmux attach-session -t "$selected_name" -c "$selected"
    exit 0
fi

# If in a tmux session...

if [[ $has_session -ne 0 ]]; then # If new session doesn't already exist, create it
    tmux new-session -d -s "$selected_name" -c "$selected"
fi

# And switch to it
tmux switch-client -t "$selected_name"

